# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9


    steps:
      - checkout
      - run: cd /etc/apt/sources.list
      - run: deb-src http://archive.debian.org/debian/ jessie main
      - run: deb http://security.debian.org jessie/updates main
      - run: deb-src http://security.debian.org jessie/updates main
      - run: sudo apt-get update
      - run: sudo apt-get install libgconf2-4 libnss3-1d libxss1
      - run: sudo npm install -g @angular/cli
      - run: sudo npm install
      - run: sudo npm cache clean -f
      - run: sudo npm install -g n
      - run: sudo n stable
      - run: sudo npm rebuild node-sass
      - run: sudo npm i node-sass@latest --unsafe-perm
      - run: sudo npm run build
    #  - run: sudo ng test --browsers ChromeHeadless --watch=false # run test Headless and exit after running unit test
